### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by t4ub3** [JuliaNeumann/event-planner-plugin#1]
styling analog wordpress Einstellungen:

> - [x]  - allgemeine Einstellungen
> - [ ] - Tabellenköpfe / Fußnoten
> - [x] - Teaser

- [x] - Teaser in Allgemeine Einstellungen
- [x] - _Allgemeines_ umbenennen in _Einstellungen_
- [ ] - Fußnoten mit in Tabellenköpfe
- [ ] - Bearbeiten-Modus für Tabellenköpfe (ggf. Infotexte dauerhaft einblenden), evtl. Ansicht als Akkordeon
